# Generated by Django 6.0.6 on 2026-07-09 05:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_skillrequest'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SkillRequest',
        ),
    ]
